{
  parserClass="kz.pompei.lanact.gen.language.ActParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Act"
  psiImplClassSuffix="Impl"
  psiPackage="kz.pompei.lanact.gen.language.psi"
  psiImplPackage="kz.pompei.lanact.gen.language.impl"

  elementTypeHolderClass="kz.pompei.lanact.gen.language.ActTokenTypes"
  elementTypeClass="kz.pompei.lanact.parser.ActElementType"
  tokenTypeClass="kz.pompei.lanact.parser.ActTokenType"


}

actFile ::= COMMENT* CLASS id statement_do_done

id ::= WORD (WORD|NUMBER)*

private statements ::= statement*

statement ::= statement_expr | statement_if | statement_do_done

statement_do_done ::= DO statements DONE

statement_expr ::= LET expression assign_part?

assign_part ::= ASSIGN expression

statement_if ::= IF expression statements statement_else_if* statement_else? END IF

expression_str ::= STR_LEFT expression (STR_INNER expression)* STR_RIGHT

statement_else_if ::= ELSIF expression statements

statement_else ::= ELSE statements

private expression ::= expr_mul | expr_add

private expr_group_primary ::= id | expr_const | expr_square | expression_str | expr_paren | statement_do_done

expr_paren ::= PAR_OPEN expression PAR_CLOSE
expr_square ::= SQ_OPEN expression SQ_CLOSE
private expr_const ::= NUMBER | YES | NO | STR_CONST

//
//
// arithmetic expressions
//
//

op_add ::= PLUS | MINUS
expr_add ::= expr_group_primary (op_mul expr_group_primary)+

op_mul ::= MUL | DIV
expr_mul ::= expr_add (op_add expr_add)*
